# Generated by Django 4.2.7 on 2024-02-26 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectAllGuestMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regis_guest_email', models.EmailField(default=False, max_length=200)),
                ('event_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventOwnerName', models.CharField(max_length=25, unique=True)),
                ('eventTitle', models.CharField(max_length=200)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('totalSeat', models.IntegerField()),
                ('eventLocation', models.CharField(max_length=250)),
                ('eventDescription', models.TextField()),
                ('token_verified', models.BooleanField(default=False)),
                ('eventCreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('eventModifyDate', models.DateTimeField(auto_now=True)),
                ('eventUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Create Event',
                'verbose_name_plural': 'Create Events',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultipleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Multiple token',
                'verbose_name_plural': 'All tokens',
            },
        ),
        migrations.CreateModel(
            name='UpdateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventOwnerName', models.CharField(max_length=150)),
                ('eventTitle', models.CharField(max_length=150)),
                ('eventDate', models.DateField(blank=True)),
                ('eventTime', models.TimeField(blank=True)),
                ('eventLocation', models.CharField(max_length=300)),
                ('eventDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('friendName', models.CharField(blank=True, max_length=50)),
                ('friendEmail', models.EmailField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('totalPerson', models.IntegerField()),
                ('token_num', models.CharField(max_length=21, unique=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.createevent')),
                ('userE', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='createevent',
            name='token_numbers',
            field=models.ManyToManyField(related_name='tokens', to='event.multipletoken'),
        ),
    ]
